// GENERATED by scripts/generate-maps.mjs — do not edit by hand.
//
// How the artwork in public/images/maps/ sits inside its viewBox. Regenerate
// this and the SVGs together with `npm run maps:generate`; a fit that does not
// match its SVG puts every pin in the wrong place.
import type { ProjectionFit } from "./projections";

export const INDIA_FIT: ProjectionFit = {
  scale: 1163.083916267004,
  translateX: 335.5460089466035,
  translateY: 270.2404948494602,
  width: 760,
  height: 610,
};

export const WORLD_FIT: ProjectionFit = {
  scale: 3.3,
  translateX: 600,
  translateY: 282.02892899999995,
  width: 1200,
  height: 472,
};
